[phases.setup]
nixPkgs = [
  "python3",
  "gcc",
  "gobject-introspection",
  "cairo",
  "pango",
  "gdk-pixbuf",
  "libffi",
  "zlib",
  "fontconfig",
  "freetype",
  "glib",
]

[start]
cmd = "gunicorn app:app"