[phases.setup]
nixPkgs = ["python3", "gcc"]
aptPkgs = [
  "libpango-1.0-0",
  "libpangocairo-1.0-0",
  "libgdk-pixbuf2.0-0",
  "libcairo2",
  "libgobject-2.0-0",
  "libglib2.0-0",
  "libffi8",
  "fonts-liberation",
  "shared-mime-info"
]
cmds = ["ldconfig"]

[variables]
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu:/usr/lib"

[start]
cmd = "gunicorn app:app"