"""agrega plan y datos_json a Pedido

Revision ID: f05231952202
Revises: 2f7de20ea484
Create Date: 2026-06-11 22:17:33.338320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05231952202'
down_revision = '2f7de20ea484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('datos_json', sa.Text(), nullable=True))
        batch_op.alter_column('url_pdf',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('pedido_usuario_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pedido_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('url_pdf',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('datos_json')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
